cheminfo/nmrium

- src/data/data1d/filter1d/lineBroadening.js
I still have to include the real flesh of the line broadening, but I'm currently blocked by the fact that I don't see how to apply lilne broadening to the demo spectra.
> very first step to include line broadening

- src/data/data1d/filter1d/lineBroadening.js
The name of the function was not correct (unfinished edition after copy/paste).
> fixed function name (and minor formatting)

- src/component/panels/InformationPanel.jsx
- src/component/panels/Panels.jsx
Here added I a new panel "InformationPanel" which shows the parameters and values of a dummy object for now. Filtering the parameter list is also possible. The dummy object should be replaced by the meta data of a Datum1D object but I was not able to figure out how to access such meta data, i.e. for an active spectrum (which actually should be the desired one?).
> Show and filter meta data from jcamp

- src/data/data1d/filter1d/phaseCorrection.js
change radians to degrees
fix first order correction
original data as input- to obtain the good behavior when interactive phase correction is doing
> phase correction - radians to degrees, fix first order correction

- src/component/header/ManualPhaseCorrectionPanel.jsx
- src/component/reducer/Reducer.js
- src/data/data1d/filter1d/phaseCorrection.js
There is one pending thing, in the current version of applyFilter (in Datum1D) it add the filter and it's not correct for manual phase correction (because add a lot of filters), so I will add again "applyManualPhaseCorrectionFilter" to Datum1D class. Fix #157
> phase correction - fix wrong behavior 

- package-lock.json
- src/component/panels/FilterPanel.jsx
- src/component/panels/IntegralTablePanel.jsx
- src/component/panels/Panels.jsx
- src/component/panels/RangesTablePanel.jsx
- src/component/panels/placeholder/NoTableData.jsx
Here, the RangesTablePanel was added. Like in case of integrals it is in the same table format.
I also added a subfolder "placeholder" and a file NoTableData.jsx. This was created to have a default view for empty tables and to use such class instead of copying and pasting the same source code every time. It is the same element which was already used, e.g. in integration table panel, if the table was empty.
> Add manual range analysis

- src/component/reducer/Reducer.js
There are two things to complete the manual phase correction where I need your help:
* Fix the issue with vertical indicator 
* We need to think how to deal with the added filters after click apply button
> refactor to show the expected behavior

- src/component/header/AutoRangesPickingOptionPanel.jsx
reduced minMaxRatio option to 0.05
> fix ranges detection

- src/component/panels/header/DefaultPanelHeader.jsx
@lpatiny and @hamed-musallam here is the modification for issue #378
> filtering icon replaced by FaFilter (font awesome)

- package-lock.json
- src/data/data1d/filter1d/digitalFilter.js
- src/data/data1d/filter1d/lineBroadening.js
- src/data/data1d/filter1d/zeroFilling.js
- src/data/metadata/getInfoFromMetaData.js
- src/data/utilities/getInfoFromMetaData.js
just adding phc1 inside the digital filter
> fix: adding phc1 in digital filter

- package-lock.json
- src/component/1d/IntegralResizable.jsx
- src/component/1d/Range.jsx
- src/component/1d/Ranges.jsx
- src/component/1d/Resizable.jsx
- src/component/reducer/Reducer.js
- src/component/reducer/actions/IntegralsActions.js
Both the Range and IntegralResizable components use the new Resizable component now to be resizable.
The Resizable component takes the from/to values when changing the size of a range or integral and saves it.
This could also be useful for other components in future, like signals.
> Ranges are resizable now (same as for integrals)

- package-lock.json
- src/data/data1d/filter1d/__tests__/digitalFilter.test.js
- src/data/data1d/filter1d/digitalFilter.js
- src/data/data1d/filter1d/lineBroadening.js
- src/data/data1d/filter1d/zeroFilling.js
- src/data/metadata/getInfoFromMetaData.js
- src/data/utilities/getInfoFromMetaData.js
Fix the test for digitalFilter
> closes #399

- package.json
- src/data/data1d/filter1d/fft.js
the dwell time was not correctly computed in the brukerconverter package (https://github.com/cheminfo-js/brukerconverter/commit/a97d70da5073b428cbb585d55525b374ce67050a#diff-23c709e764e20ce8dfbe0da0f0c837f4R313). By correcting this issue we introduced broke the ppm scale in this project. This PR solves this problem.
> fix: fixing ppm scale that was broken by #395

- src/component/modal/ChangeSumModal.jsx
- src/component/panels/IntegralTablePanel.jsx
- src/component/panels/RangesTablePanel.jsx
- src/component/panels/preferences-panels/defaultValues.js
In the change range/integral sum modal, the user can now select a molecule in a view to set the reference value (sum).
Also the "nb" is replaced by "Relative" of an element in RangesTablePanel. As in IntegralTablePanel, but only controlled by default settings.
> Set sum from molecule 

- package-lock.json
- package.json
- src/component/panels/MoleculePanel.jsx
I replaced it in MoleculePanel only. In ChangeSumModal, nothing has changed since it might not be needed there.
> replaced MolfileSvgRenderer by OCLnmr in MoleculePanel (issue #482)

- package-lock.json
- src/component/1d/MultiplicityTree.jsx
- src/component/1d/Range.jsx
- src/component/highlight/index.js
- src/component/panels/MoleculePanel.jsx
- src/component/panels/RangesPanel/RangesTable.jsx
- src/component/panels/RangesPanel/RangesTablePanel.jsx
- src/component/panels/RangesPanel/RangesTableRow.jsx
- src/component/panels/extra/utilities/MultiplicityUtilities.js
- src/component/panels/extra/utilities/RangeUtilities.js
- adaption of ranges table according to #537 
- full control for the user where to store assignments (range vs. signal level)
> Improvement of signal and range level storage

- package-lock.json
- package.json
It fixes an error at matrix-peaks-finder it is the algorithm that detects the peaks on a 2D zone
> fix: close #654

- package-lock.json
- package.json
- src/component/header/AutoPeakPickingOptionPanel.jsx
- src/component/header/RangesPickingOptionPanel.jsx
- src/component/reducer/actions/IntegralsActions.js
- src/data/data1d/Datum1D.js
- src/data/data1d/autoPeakPicking.js
fix wrong typo and wrong behavior of peak detection
> feat: add negative 1D signals detection

- src/data/correlation/CorrelationManager.js
- src/data/data1d/Datum1D.js
> add signal id when adding a range manually

- package-lock.json
- package.json
> fix: update nmr-parser

- src/component/2d/Contours.jsx
> chore: single path component for each positive and negative

- src/data/data2d/Datum2D.ts
create a zone per each signal detected when a zone is defined manually in 2D peak picking tool.
> feat: (2D pp) create a zone per each signal detected 

- src/component/1d/Viewer1D.jsx
- src/component/2d/Viewer2D.jsx
- src/component/NMRium.tsx
- src/component/loader/NoData.jsx
- src/component/loader/Spinner.jsx
- src/demo/views/View.jsx
> feat-emptyText-props

- src/data/data1d/filter1d/baselineCorrection.js
> fix: always use the zones for polynomial baseline correction.

- src/component/reducer/actions/PreferencesActions.ts
Closes: https://github.com/cheminfo/nmrium/issues/1345
> Resolve crash on recall zoom level

- src/component/panels/SpectrumsPanel/base/setting/Spectrum2DHistogram.tsx
Closes: https://github.com/cheminfo/nmrium/issues/1336
> Change san plot text to be displayed in one line

- src/component/1d/ranges/Ranges.tsx
Closes: https://github.com/cheminfo/nmrium/issues/1353
> Resolve missing key error

- src/component/1d/Line.tsx
- src/component/1d/utilities/useIntegralPath.ts
- src/component/2d/Left1DChart.tsx
- src/component/2d/Top1DChart.tsx
- src/component/2d/tools/slicing/HorizontalSliceChart.tsx
- src/component/2d/tools/slicing/VerticalSliceChart.tsx
- src/component/utility/PathBuilder.ts
Closes: https://github.com/cheminfo/nmrium/issues/1351
> Change string append to use d3-path

- src/component/2d/Left1DChart.tsx
- src/component/2d/tools/slicing/VerticalSliceChart.tsx
Closes: https://github.com/cheminfo/nmrium/issues/1351
> refactor: change moveTo to use directly value instead of a variables

- src/component/2d/Contours.tsx
- src/component/utility/PathBuilder.ts
Closes: https://github.com/cheminfo/nmrium/issues/1338
> Resolve shifting issue with chart 2d

- src/component/panels/Panels.tsx
Closes: https://github.com/cheminfo/nmrium/issues/1368
> Open Zone panel while you click on the sidebar

- src/component/1d/Viewer1D.tsx
- src/component/reducer/actions/RangesActions.ts
- src/data/data1d/Spectrum1D/ranges/addRange.ts
- src/data/data1d/Spectrum1D/ranges/detectSignal.ts
close https://github.com/cheminfo/nmrium/issues/1328
> feat: prevent crash with multiplet analysis

- src/component/EventsTrackers/BrushTracker.tsx
Fixes: https://github.com/cheminfo/nmrium/issues/1370
> fix: resolve error on zoom

- package-lock.json
- package.json
- src/component/loader/DropZone.tsx
- src/data/PredictionManager.ts
- src/data/types/data2d/Signal2D.ts
> fix: generateSpectrum2D n getFrequency function

- CITATION.cff
> chore: add orcid to CITATION.cff

- package-lock.json
- package.json
- src/data/SpectraManager.ts
- src/data/data1d/Data1DManager.ts
> fix: update nmr-parser to 1.9.0

- src/component/panels/databasePanel/DatabasePanel.tsx
loading large database
update of database when changing nucleus
closes: #1613 #1614
> feat: improve loading database

- src/component/reducer/actions/FiltersActions.ts
- src/data/data1d/Data1DManager.ts
> fix: round data to dataPoints reported

- test-e2e/panels/structures.test.ts
closes : https://github.com/cheminfo/nmrium/issues/1693#event-7173446797
> Improve molecule test

- playwright.config.ts
- src/component/panels/MoleculesPanel/MoleculePanelHeader.tsx
- test-e2e/panels/structures.test.ts
closes : https://github.com/cheminfo/nmrium/issues/1703
> 1h spectrum molecules test

- src/component/elements/MoleculeSelection.tsx
- src/component/modal/MoleculeStructureEditorModal.tsx
- src/component/modal/changeSum/ChangeSumModal.tsx
- src/component/modal/changeSum/SelectMolecule.tsx
- src/component/panels/MoleculesPanel/MoleculeHeader.tsx
- src/component/panels/MoleculesPanel/MoleculePanel.tsx
- src/component/panels/MoleculesPanel/MoleculePanelHeader.tsx
- src/component/reducer/actions/MoleculeActions.ts
- src/component/tool/FloatMoleculeStructures/DraggableStructure.tsx
- src/component/tool/FloatMoleculeStructures/index.tsx
- src/data/data1d/Spectrum1D/SumManager.ts
- src/data/data1d/Spectrum1D/integrals/changeIntegralsRelative.ts
- src/data/data1d/Spectrum1D/ranges/changeRangeRelativeValue.ts
- src/data/molecules/Molecule.ts
- src/data/molecules/MoleculeManager.ts
- src/data/types/data1d/SumOptions.ts
closes : https://github.com/cheminfo/nmrium/issues/1700
> chore: rename moleculeKey to moleculeId

- src/component/reducer/actions/LoadActions.ts
- src/data/SpectraManager.ts
- src/data/molecules/MoleculeManager.ts
- src/types/NMRiumDataReturn.ts
closes https://github.com/cheminfo/nmrium/issues/1719
> fix: import molecules id on loading json data

- src/component/elements/MoleculeSelection.tsx
- src/component/modal/MoleculeStructureEditorModal.tsx
- src/component/panels/MoleculesPanel/MoleculeHeader.tsx
- src/component/panels/MoleculesPanel/MoleculePanel.tsx
- src/component/panels/MoleculesPanel/MoleculePanelHeader.tsx
- src/component/panels/RangesPanel/RangesPanel.tsx
- src/component/panels/predictionPanel/PredictionPanel.tsx
- src/component/reducer/Reducer.ts
- src/component/reducer/actions/LoadActions.ts
- src/component/tool/FloatMoleculeStructures/DraggableStructure.tsx
- src/component/tool/FloatMoleculeStructures/index.tsx
- src/data/SpectraManager.ts
- src/data/data1d/Spectrum1D/SumManager.ts
- src/data/molecules/Molecule.ts
- src/data/molecules/MoleculeManager.ts
- src/types/NMRiumDataReturn.ts
closes https://github.com/cheminfo/nmrium/issues/1727
> chore: rename Molecule types

- src/component/1d/ExclusionZoneAnnotation.tsx
- src/component/1d/IntegralResizable.tsx
- src/component/1d/database/DatabaseElements.tsx
- src/component/1d/database/DatabaseSpectrum.tsx
- src/component/1d/database/ResurrectedDatabaseRanges.tsx
- src/component/1d/multiplicityTree/MultiplicityTree.tsx
- src/component/1d/peaks/PeakAnnotation.tsx
- src/component/1d/ranges/Range.tsx
- src/component/2d/zones/Zone.tsx
- src/component/EventsTrackers/KeysListenerTracker.tsx
- src/component/assignment/AssignmentsContext.ts
- src/component/elements/ReactTable/Elements/ReactTableRow.tsx
- src/component/elements/ReactTable/ReactTable.tsx
- src/component/highlight/index.tsx
- src/component/panels/MoleculesPanel/Utilities.ts
- src/component/panels/MoleculesPanel/useAtomAssignment.tsx
- src/component/panels/RangesPanel/RangesTableRow.tsx
- src/component/panels/RangesPanel/TableColumns/RangeAssignmentsColumn.tsx
- src/component/panels/RangesPanel/TableColumns/SignalAssignmentsColumn.tsx
- src/component/panels/databasePanel/DatabaseTable.tsx
closes https://github.com/cheminfo/nmrium/issues/1658
> Sync highlight molecules

- src/demo/samples.json
- src/demo/views/Test.tsx
- src/demo/views/View.tsx
closes https://github.com/cheminfo/nmrium/issues/1749
> Improve test view

- src/component/elements/popup/Modal/Provider.tsx
closes https://github.com/cheminfo/nmrium/issues/1706
> fix dialog box position

- .eslintrc.yml
- package-lock.json
- package.json
- src/component/NMRium.tsx
- chore: update dependencies
- fix: support changing onViewChange callback
> Fix onViewChange callback

- src/component/2d/tools/slicing/VerticalSliceChart.tsx
> fix: vertical axis for the slicing tool

- src/component/elements/ReactTable/ReactTableFlexLayout.tsx
- src/component/panels/InformationPanel.tsx
> refactor: information panel

- src/component/panels/databasePanel/DatabaseTable.tsx
> fix: coupling constants format

- src/component/elements/ReactTable/ReactTable.tsx
- src/component/panels/PeaksPanel/PeaksTable.tsx
- src/component/panels/databasePanel/DatabasePanel.tsx
- src/component/panels/databasePanel/DatabaseTable.tsx
- src/data/data1d/database.ts
- test-e2e/panels/filters.test.ts
a demo for a sticky footer counter under the table when the virtual scroll activated 
close #1854
> feat: database table scroll position

- src/component/panels/MultipleSpectraAnalysisPanel/MultipleSpectraAnalysisPanel.tsx
- src/component/panels/MultipleSpectraAnalysisPanel/MultipleSpectraAnalysisPreferences.tsx
> fix: multiple spectra analysis columns preferences

- src/component/reducer/actions/FiltersActions.ts
- src/data/data1d/filter1d/exclusionZones.ts
- test-e2e/panels/filters.test.ts
- test-e2e/panels/integral.test.ts
- test-e2e/panels/peaks.test.ts
- test-e2e/panels/ranges.test.ts
- test-e2e/utilities/selectRange.ts
> fix: exclusion zones

- test-e2e/core/basic.test.ts
- test-e2e/panels/structures.test.ts
Event count is different in React dev mode.
> test: fix e2e test with local dev server

- src/component/modal/setting/DisplayTabContent.tsx
- src/component/panels/Panels.tsx
- src/component/workspaces/process1D.ts
- src/types/NMRiumPanelPreferences.ts
> feat: display matrix generation panel

- src/component/panels/SpectrumsPanel/SpectraPanelHeader.tsx
- src/component/panels/SpectrumsPanel/SpectrumListPanel.tsx
- src/component/panels/SpectrumsPanel/SpectrumsTabs.tsx
- src/component/reducer/actions/SpectrumsActions.ts
> fix: hide/show spectra

- src/component/loader/DropZone.tsx
- src/component/reducer/Reducer.ts
- src/component/reducer/actions/LoadActions.ts
- src/component/reducer/actions/ToolsActions.ts
> feat: show a message when drag/drop files raise an error

- src/component/panels/MultipleSpectraAnalysisPanel/MultipleSpectraAnalysisPreferences.tsx
delete columns from multiple spectra analysis preferences
remove index column
close #1921
> feat: improve multiple spectra analysis panel

- src/component/panels/SpectrumsPanel/SpectraPanelHeader.tsx
> refactor: hide projection button for 2D fid

- test-e2e/panels/spectra.test.ts
closes https://github.com/cheminfo/nmrium/issues/1959
> test: show/hide spectrum

- src/data/data1d/Spectrum1D/ranges/addRange.ts
- src/data/data1d/Spectrum1D/ranges/changeRange.ts
- src/data/data1d/Spectrum1D/ranges/detectSignal.ts
> feat: redetect signal when resizing the range

- package-lock.json
- package.json
- src/component/modal/LoadJCAMPModal.tsx
- src/component/reducer/actions/SpectraAnalysisAction.ts
- src/component/toolbar/BasicToolBar.tsx
- src/component/utility/FileUtility.ts
- src/data/SpectraManager.ts
- src/demo/layouts/Main.tsx
- src/demo/views/Test.tsx
- test-e2e/core/import.test.ts
- fix: support .jcamp extensions
- chore: remove unused file utils
> Cleanup and allow .jcamp files

- src/component/1d/multiAnalysis/AnalysisRange.tsx
- src/component/1d/multiAnalysis/MultiAnalysisRanges.tsx
- src/data/data1d/multipleSpectraAnalysis.ts
> refactor: multiple spectra analysis

- src/component/header/ApodizationOptionsPanel.tsx
- src/component/header/AutoPeakPickingOptionPanel.tsx
- src/component/header/BaseLineCorrectionPanel.tsx
- src/component/header/Header.tsx
- src/component/header/HeaderContainer.tsx
- src/component/header/ManualPhaseCorrectionPanel.tsx
- src/component/header/RangesPickingOptionPanel.tsx
- src/component/header/ZeroFillingOptionsPanel.tsx
- src/component/header/Zones2DOptionPanel.tsx
> style: top toolbar

- src/component/panels/SpectrumsPanel/SpectraTable.tsx
- src/data/types/common/Info.ts
- src/data/types/data1d/Info1D.ts
- src/data/types/data2d/Info2D.ts
> fix: sorting by solvent

- src/component/EventsTrackers/KeysListenerTracker.tsx
> chore: remove code line duplication

- .github/workflows/e2e.yml
- .github/workflows/nodejs.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- package-lock.json
- package.json
- playwright.config.ts
- src/component/utility/export.ts
- test-e2e/NmriumPage.ts
- test-e2e/core/basic.test.ts
- test-e2e/panels/autoassignment.test.ts
- test-e2e/panels/spectra.test.ts
This hopefully fixes the problems with Playwright on Firefox.
> chore: update dependencies

- src/component/panels/SpectrumsPanel/SpectraTable.tsx
- test-e2e/NmriumPage.ts
- test-e2e/panels/filters.test.ts
- test-e2e/panels/structures.test.ts
> refactor: enable virtual scroll on the spectra list

- src/component/reducer/preferences/panelsPreferencesDefaultValues.ts
> refactor: change Pulse sequence column jpath

- public/data/aspirin/bruker_aspirin_zip.json
- public/data/cytisine/1H_Cytisin_linkJcamp.json
- src/data/data1d/Spectrum1D/ranges/addRange.ts
- src/data/data1d/Spectrum1D/ranges/detectSignal.ts
- src/data/types/data1d/Datum1D.ts
- src/demo/samples.json
> handle the range picking of a singlet correctly

- src/component/hooks/useToolsFunctions.ts
- test-e2e/panels/autoassignment.test.ts
> fix: set the zoom tool active when deselecting another tool

- src/component/reducer/actions/ToolsActions.ts
> feat: change contours levels for all 2d spectra if no spectrum is selected

- src/component/1d/jCouplingGraph/JGraph.tsx
- src/component/1d/ranges/Ranges.tsx
> refactor: hide ranges and j-graph when hide the spectrum

- test-e2e/panels/autoassignment.test.ts
> Revert "test: wait for auto zones/range detection to be finished"

- package-lock.json
- package.json
- public/data/cytisine/2d/jresolv.json
- src/component/reducer/actions/FiltersActions.ts
- src/data/data1d/filter1d/fft.ts
- src/data/data1d/filter1d/phaseCorrection.ts
- src/data/types/common/Info.ts
- src/data/types/data1d/Info1D.ts
- src/demo/samples.json
.SHIFT REFERENCE is used to calculate the frequencyOffset that is used to calculate the first point value of ppm axis. it is ignore if SFO1, BF1 exists.
REVERSE is checked after FFT filter is applied to reverse the data.
close #1152 #1634
> new LDR supported and phase correction if parameters exists

- src/component/loader/DropZone.tsx
- src/component/reducer/Reducer.ts
- src/component/reducer/actions/LoadActions.ts
- src/component/reducer/actions/SpectrumsActions.ts
- test-e2e/core/basic.test.ts
- test-e2e/panels/structures.test.ts
* feat: load .nmrium file without spectra and have `view` or, and `settings` objects
close #2100
* test: update viewCount and dataCount
> feat: load .nmrium file without spectra (#2123)

- src/component/modal/PredictSpectraModal.tsx
> refactor: 'from' and 'to' fields validation to accept a float number

- src/component/header/ZeroFillingOptionsPanel.tsx
> fix: re-edition of zero filling

- src/component/panels/PeaksPanel/PeaksPanel.tsx
> style: optimize Peaks button

- src/component/reducer/actions/LoadActions.ts
> fix: empty test cases not working

- src/component/reducer/actions/IntegralsActions.ts
- src/component/reducer/actions/SpectrumsActions.ts
> refactor: access activeTab object

- src/component/elements/popup/Modal/ConfirmDialog.tsx
- src/component/panels/filtersPanel/FilterPanel.tsx
- src/component/panels/filtersPanel/FiltersTable.tsx
> refactor: alert messages for filters deletion

- src/component/panels/SpectrumsPanel/SpectraPanelHeader.tsx
> refactor: alert message for the spectra deletion

- src/component/panels/SpectrumsPanel/SpectrumsTabs.tsx
> fix: avoid unmounts in spectra panel

- src/component/panels/MoleculesPanel/MoleculePanelHeader.tsx
- test-e2e/panels/structures.test.ts
> feat: copy molfile as V3 or V2

- src/component/1d/Chart1D.tsx
- src/component/1d/integral/IntegralIndicator.tsx
- src/component/2d/Chart2D.tsx
- src/component/elements/resizer/SVGResizer.tsx
- src/component/modal/setting/settings-tabs/GeneralTabContent.tsx
- src/component/workspaces/Workspace.ts
- src/component/workspaces/workspaceDefaultProperties.ts
https://github.com/cheminfo/nmrium/issues/2166
> fix: use svg transform instead of css transform

- src/component/1d/FooterBanner.tsx
- src/component/2d/FooterBanner.tsx
- src/component/elements/Button.tsx
- src/component/elements/Header.tsx
- src/component/elements/InputRange.tsx
- src/component/elements/Label.tsx
- src/component/elements/dropDownButton/DropDownButton.tsx
- src/component/header/ApodizationOptionsPanel.tsx
- src/component/header/AutoPeakPickingOptionPanel.tsx
- src/component/header/BaseLineCorrectionPanel.tsx
- src/component/header/Header.tsx
- src/component/header/ManualPhaseCorrectionPanel.tsx
- src/component/header/RangesPickingOptionPanel.tsx
- src/component/hooks/useToolsFunctions.ts
- test-e2e/panels/structures.test.ts
closes: https://github.com/cheminfo/nmrium/issues/2211
> style: adapt header and footer to work on small container size

- src/component/header/Header.tsx
- src/demo/Sidebar.tsx
- src/demo/layouts/Admin.tsx
- src/demo/layouts/Main.tsx
- src/demo/layouts/SingleDisplayerLayout.tsx
- src/demo/samples.json
- src/demo/utility/menu.ts
- src/demo/views/SnapshotView.tsx
- src/demo/views/View.tsx
- src/demo/views/index.ts
> demo: control NMRium container width and height

- package-lock.json
- package.json
- src/component/context/LoggerContext.tsx
- src/component/header/LogsHistory.tsx
- src/component/loader/DropZone.tsx
- src/component/modal/setting/settings-tabs/GeneralTabContent.tsx
- src/component/workspaces/Workspace.ts
- src/component/workspaces/workspaceDefaultProperties.ts
> refactor: Improve logging system

- src/data/data1d/Spectrum1D/initiateDatum1D.ts
> fix: onload processing

- src/component/elements/Tab/Tabs.tsx
- src/component/header/Header.tsx
- src/component/hooks/useSaveSettings.tsx
- src/component/modal/setting/GeneralSettings.tsx
- test-e2e/panels/autoassignment.test.ts
- test-e2e/panels/filters.test.ts
closes : https://github.com/cheminfo/nmrium/issues/2156
> reimplement general setting and save settings modals

- test-e2e/panels/spectra.test.ts
closes: https://github.com/cheminfo/nmrium/issues/2164
> Testcases for source

- src/component/reducer/actions/ToolsActions.ts
- src/component/reducer/helper/ZoomHistoryManager.ts
> fix: horizontal zoom out

- src/component/elements/ReactTable/Elements/ReactTableRow.tsx
- test-e2e/core/setting.test.ts
- test-e2e/panels/filters.test.ts
move the dropdown menu component to table cells
close #2292
> fix: react-table layout

- src/component/header/Header.tsx
- src/component/header/PhaseCorrectionPanel.tsx
ph0 input value should start from its last changed value
close #2314
> fix: ph0 value starts from zero

- src/component/context/PreferencesContext.tsx
- src/component/reducer/preferences/preferencesReducer.ts
> fix: erase setting completely when the settings version changed

- src/component/reducer/actions/LoadActions.ts
- src/data/molecules/MoleculeManager.ts
> fix: structures labels uniqueness

- src/component/panels/RangesPanel/RangesTable.tsx
> feat: add 'title' attribute over assign ranges and signals column

- src/demo/samples.json
- src/demo/views/WebSourceView.tsx
- src/demo/views/index.ts
> demo: load spectra with nmr-load-save package

- src/component/1d/ranges/Range.tsx
- src/data/data1d/Spectrum1D/isRangeAssigned.ts
display yellow rectangle  as an indicator on the top of the ranges when the range or its signal assigned to atoms
close #2338
> feat: display assigned indicator over ranges

- src/data/data1d/Spectrum1D/initiateDatum1D.ts
- src/data/data2d/Spectrum2D/initiateDatum2D.ts
closes: https://github.com/cheminfo/nmrium/issues/2359
> fix: spectrum object should include the sourceSelector

- src/component/modal/editRange/EditRangeModal.tsx
> fix: manual coupling edition

- src/component/elements/MolecularFormulaInput.tsx
- src/component/loader/DropZone.tsx
- src/component/panels/databasePanel/DatabasePanel.tsx
- src/data/data1d/database.ts
- refactor: do not report error while validating MF
- refactor: do not report error for invalid dropped files
- refactor: do not report error when database fails to load
- refactor: do not report error while parsing molecules
> Remove some reportError

- src/component/1d-2d/tools/BrushX.tsx
- src/component/1d-2d/tools/BrushXY.tsx
- src/component/1d-2d/tools/CrossLinePointer.tsx
- src/component/1d/FooterBanner.tsx
- src/component/1d/SpectraLegends.tsx
- src/component/1d/Viewer1D.tsx
- src/component/1d/tool/PeakPointer.tsx
- src/component/1d/tool/XLabelPointer.tsx
- src/component/2d/FooterBanner.tsx
- src/component/2d/Viewer2D.tsx
- src/component/2d/tools/XYLabelPointer.tsx
- src/component/EventsTrackers/BrushTracker.tsx
- src/component/EventsTrackers/MouseTracker.tsx
- src/component/modal/MultipletAnalysisModal.tsx
- src/component/reducer/actions/ToolsActions.ts
the bugs happen because the `DOWN` action in the brush reducer does not return the state on certain conditions.
> refactor: brush and mouse context

- src/component/header/AutoPeakPickingOptionPanel.tsx
- src/component/header/RangesPickingOptionPanel.tsx
- src/component/hooks/useCheckPointsNumberInWindowArea.ts
- src/component/panels/RangesPanel/RangesHeader.tsx
- src/component/reducer/actions/RangesActions.ts
- src/data/data1d/Spectrum1D/ranges/addRange.ts
> fix: auto (peaks and ranges) picking  window size

- src/component/panels/MoleculesPanel/MoleculePanelHeader.tsx
- src/component/panels/header/DefaultPanelHeader.tsx
- src/component/panels/header/PanelHeader.tsx
- test-e2e/panels/structures.test.ts
- refactor 'export as' dropdown menu
- create general 'header' component wrapper
> refactor: molecule header panel

- src/component/modal/metaImportation/MetaImportationModal.tsx
> fix: check the meta file has an accepted mimeType

- src/component/panels/SpectrumsPanel/SpectraTable.tsx
> fix: hide spectrum settings dialog if it's 2d Fid

- test-e2e/panels/spectra.test.ts
closes : https://github.com/cheminfo/nmrium/issues/2389
> test: load jresolv

- test-e2e/panels/ranges.test.ts
closes : https://github.com/cheminfo/nmrium/issues/2412
> test: spectra automatic picking

- src/component/context/LoggerContext.tsx
- src/component/header/Header.tsx
- src/component/header/LogsHistory.tsx
- src/component/modal/LogsHistoryModal.tsx
if we have a new  warn, error or fatal the logger dialog should be opened automatically
close #2485
> feat: open logger dialog automatically

- package-lock.json
- package.json
Closes: https://github.com/cheminfo/nmrium/issues/2497, NMRIUM-ORG-R
Refs: https://github.com/cheminfo/nmrium/pull/2499
> chore: update nmr-processing

- src/component/modal/PredictSpectraModal.tsx
- src/component/panels/MoleculesPanel/MoleculePanelHeader.tsx
Refs: https://github.com/cheminfo/nmrium/issues/1537
> refactor PredictSpectraModal using react-science

- src/component/1d-2d/tools/BrushXY.tsx
- src/component/1d/FooterBanner.tsx
- src/component/1d/Viewer1D.tsx
- src/component/2d/FooterBanner.tsx
- src/component/2d/Viewer2D.tsx
- src/component/EventsTrackers/BrushTracker.tsx
- src/component/reducer/Reducer.ts
- src/component/reducer/actions/DomainActions.ts
1D pan horizontally and 2D pan vertically and horizontally by pressing the secondary mouse button which is the left one or depending on your configuration
- #2477
> feat: 1D pan horizontally and 2D pan vertically and horizontally

- playwright.config.ts
- src/component/NMRium.tsx
- src/component/elements/popup/Alert/AlertBlock.tsx
- src/component/elements/popup/Alert/Context.ts
- src/component/elements/popup/Alert/Provider.tsx
- src/component/elements/popup/options.ts
- src/component/hooks/useExport.tsx
- src/component/reducer/Reducer.ts
try-catch the reducer and set errorAction in state on catch Also I typed the Alert API from useAlert / AlertContext
Closes: https://github.com/cheminfo/nmrium/issues/2481
> fix: unexpected errors in reducer crashing the app

- package-lock.json
- package.json
ensure cosine similarity at check similarity
> fix: manual range multiplicity

- src/component/panels/MoleculesPanel/MoleculePanelHeader.tsx
- src/component/reducer/Reducer.ts
- src/component/reducer/actions/MoleculeActions.ts
- src/data/molecules/MoleculeManager.ts
> feat: paste / import a list of structures

- src/component/utility/PathBuilder.ts
Closes: https://github.com/cheminfo/nmrium/issues/2517
> fix: clamp SVG paths to avoid rendering issues

- package-lock.json
- src/component/modal/changeSum/ChangeSumModal.tsx
- src/component/panels/IntegralsPanel/IntegralPanel.tsx
- src/component/panels/RangesPanel/RangesHeader.tsx
- test-e2e/panels/structures.test.ts
refs: https://github.com/cheminfo/nmrium/issues/1537
> Refactor ChangeSumModal using react-science modal 

- package-lock.json
- package.json
- src/component/modal/changeSum/ChangeSumModal.tsx
- src/component/modal/changeSum/ChangeSumModalContents.tsx
- src/component/panels/IntegralsPanel/IntegralPanel.tsx
- src/component/panels/RangesPanel/RangesHeader.tsx
- test-e2e/panels/structures.test.ts
- chore: remove unused onClose callback
- chore: simplify ChangeSumModal usage
- fix: do not render two buttons in ChangeSumModal
- refactor: drastically simplify ChangeSumModal
- refactor: only render ChangeSumModal contents when open
> Fix and improve ChangeSumModal

- src/component/assignment/index.tsx
- src/component/main/InnerNMRium.tsx
- src/component/main/InnerNMRiumContents.tsx
- src/component/main/NMRiumStateProvider.tsx
- refactor: move main state provider to its own file
- chore: trace-log each main dispatched action
> Move main state provider and trace-log actions

- vite.config.ts
- https://github.com/cheminfo/nmrium/issues/2585
> demo: fix menu background color

- src/component/1d/Viewer1D.tsx
- src/component/reducer/Reducer.ts
- src/component/reducer/actions/IntegralsActions.ts
- src/component/reducer/actions/RangesActions.ts
- src/data/data1d/Spectrum1D/ranges/addRange.ts
> feat: cut integral

- src/component/1d/integral/IntegralResizable.tsx
- src/component/1d/multiAnalysis/AnalysisRange.tsx
- src/component/1d/ranges/Range.tsx
- src/component/context/KeyModifierContext.tsx
- src/component/hooks/useResizerStatus.ts
- src/component/main/InnerNMRium.tsx
> refactor: ranges, integrals, and multiplet analysis resizing 

- src/component/2d/zones/Signal.tsx
- test-e2e/panels/ranges.test.ts
closes : https://github.com/cheminfo/nmrium/issues/2590
> 2D spectra reference change

- src/component/header/ApodizationOptionsPanel.tsx
- src/component/header/BaseLineCorrectionPanel.tsx
- src/component/header/ZeroFillingOptionsPanel.tsx
- src/component/reducer/Reducer.ts
- src/component/reducer/actions/FiltersActions.ts
refactor: apodization filter options panel and action
refactor : baseline correction options panel and action
refactor : zero filling options panel and action
> fix: filters live preview

- package-lock.json
- package.json
> fix: correct the integration sum for integrals and ranges

- src/component/1d-2d/components/FloatMoleculeStructures/DraggableStructure.tsx
- src/component/modal/MoleculeStructureEditorModal.tsx
- src/component/panels/MoleculesPanel/MoleculePanel.tsx
- src/component/panels/predictionPanel/PredictionPanel.tsx
closes : https://github.com/cheminfo/nmrium/issues/2608
> Refactor MoleculeStructureEditorModal

- package-lock.json
- package.json
> fix: recalculate integration when toggling or deleting filter

- src/component/2d/Viewer2D.tsx
> fix: do not raise an error if no 1D trace spectra are found

- package-lock.json
- package.json
- src/component/header/Header.tsx
- src/component/workspaces/embedded.ts
- src/component/workspaces/workspaceDefaultProperties.ts
close #2642
Control the visibility of those items (help,logs, general setting, workspaces and maximize) from the workspace preferences
> feat: control the visibility of NMRium header items

- package-lock.json
- package.json
improving bruker loading speed by parallel reading
> improve bruker files loading and fix compressed nmrRecord loading

- src/component/context/KeyModifierContext.tsx
- src/component/panels/SpectrumsPanel/SpectrumsTabs.tsx
Determine the key modifier based on the host OS, use 'CMD' for Mac and 'Ctrl' for other OS.
close #2664
> fix: consecutive selection

- package-lock.json
- package.json
- tsconfig.json
This reverts commit a88408530256dc2b32efecffa1fabf069bff4c24.
> Revert "chore: update typescript to version 5.2.2"

- src/component/panels/SpectrumsPanel/SpectraPreferences.tsx
> fix: filter spectrum columns correctly

- src/component/EventsTrackers/BrushTracker.tsx
- src/component/elements/draggable/SVGDraggable.tsx
- src/component/elements/draggable/useDraggable.ts
- src/component/elements/resizer/DivResizer.tsx
- src/component/elements/resizer/SVGResizer.tsx
Change the event in the bruch tool to support other types of pointing, like, touch
> feat: change mouse event to pointer event

- src/component/panels/RangesPanel/RangesTable.tsx
- src/component/panels/RangesPanel/hooks/useMapRanges.ts
> fix: add range with no signals

- src/component/context/LoggerContext.tsx
> fix: open the log history automatically if we have error or fatal

- package-lock.json
- package.json
- src/component/toolbar/BasicToolBar.tsx
- src/demo/layouts/Admin.tsx
- Disable React StrictMode.
- Do not pass `isOpen` to div.
Refs: https://github.com/zakodium-oss/react-science/issues/610
> fix: Blueprint-related warnings

- src/component/panels/SpectrumsPanel/SpectraTable.tsx
- src/component/panels/SpectrumsPanel/base/RenderAsHTML.tsx
- src/component/reducer/preferences/panelsPreferencesDefaultValues.ts
> feat: allow to delete info.name and info.solvent

- src/data/data1d/multipleSpectraAnalysis.ts
formula cell object should include the spectra ID
close #2834
> fix: plotting the derived value

- src/component/reducer/actions/FiltersActions.ts
> fix: reapply filters when applying spectra processing filter

- src/component/panels/databasePanel/DatabasePanel.tsx
> fix: remove empty values from search key array

- src/component/1d/Line.tsx
- src/component/1d/LinesSeries.tsx
- src/component/1d/utilities/scale.ts
- src/component/context/KeyModifierContext.tsx
- src/component/hooks/useSetActiveSpectrumAction.ts
- src/component/panels/SpectrumsPanel/SpectrumsTabs.tsx
- src/component/reducer/helper/getVerticalAlign.ts
> feat: select spectrum from the displayer

- src/component/panels/spectrumSimulation/SpectrumSimulation.tsx
> fix: validate spin system data

- src/component/panels/RangesPanel/RangesTable.tsx
> feat: sort ranges by chemical shifts

- src/component/1d/Viewer1D.tsx
- src/component/1d/tool/BaseLine.tsx
> feat: display horizontal line at y = 0 for phase and baseline correction

- src/component/header/Header.tsx
> feat: add a link to NMRium videos channel

- package-lock.json
- package.json
- src/component/elements/Input.tsx
- src/component/header/BaseLineCorrectionPanel.tsx
- src/component/reducer/actions/FiltersActions.ts
- src/component/reducer/actions/LoadActions.ts
- src/component/reducer/actions/ToolsActions.ts
- test-e2e/NmriumPage/index.ts
- test-e2e/panels/filters.test.ts
> fix: correct rollback spectrum behaviour

- src/component/1d/SimilarityTree.tsx
change similarity tree node and text color
> refactor: show the similarity tree only for 1D spectrum

- src/component/reducer/actions/FiltersActions.ts
- test-e2e/panels/filters.test.ts
> fix: pass the data to the filter before the filter affects it

- src/component/1d/Chart1D.tsx
Ensuring that peaks are rendered in front of the ranges
> refactor: rearranging the rendering order of ranges and their peaks

- src/component/modal/ImportPublicationStringModal.tsx
- src/component/toolbar/ToolBar.tsx
> fix: re-initialize FifoLogger instance when opening the modal

- package-lock.json
- package.json
date and epoch added to info from bruker, jcamp and jeol formats
> fix: add more gyromagnetic ratio constants

- public/data/cytisine/full-config-sample.json
- src/component/reducer/preferences/actions/setWorkspace.ts
It seems that despite asking to hide workspace and preferences button they are still there.
@hamed-musallam Is this normal ?
> test: remove workspace in full-config-sample

- src/component/1d/integral/IntegralsSeries.tsx
- src/component/1d/integral/Integration.tsx
- src/component/1d/ranges/RangesIntegrals.tsx
- src/component/hooks/useIntegralPath.ts
> fix: recalculate integral reducer points based on the zoom range

- src/component/1d/Viewer1D.tsx
- src/component/panels/MatrixGenerationPanel/MatrixGenerationPanel.tsx
fix: toggle the matrix generation exclusion zones tool
fix: select stocsy pivot point when the  exclusion zones tool selected
> refactor: improve matrix generation

- src/component/panels/Panels.tsx
- test-e2e/panels/ranges.test.ts
- test-e2e/panels/settings.test.ts
- test-e2e/panels/structures.test.ts
> refactor: rename panel 'Ranges' to 'Ranges / Multiplet analysis'

- src/component/panels/filtersPanel/FiltersTable.tsx
- src/component/reducer/actions/FiltersActions.ts
> fix: rollback to digital filter

- src/component/panels/databasePanel/DatabasePanel.tsx
- src/component/panels/databasePanel/DatabasePreferences.tsx
replace Formik with react-form-hook
> refactor: database preferences

- src/component/modal/ImportPublicationStringModal.tsx
- Replace Formik with react-form-hook
- Switch input fields to BlueprintJS components
> refactor: import publication string modal

- src/component/modal/metaImportation/MetaImportationModal.tsx
- src/data/parseMeta/linkMetaWithSpectra.ts
- Replace Formik with react-form-hook
- Switch input fields to BlueprintJS components
> refactor: meta importation modal

- src/component/main/InnerNMRiumContents.tsx
> refactor: lifting the filter provider up

- package-lock.json
- package.json
chore: update vitest to version 3.0.3
close #3310
> chore: update vite to version 6

- src/component/panels/MoleculesPanel/MoleculePanelHeader.tsx
Bug was introduced by https://github.com/cheminfo/nmrium/commit/683eb63d2ca33cf2b5886eb5793f1f2ac8d5af38
> fix: molecule export as SVG

- src/component/1d/BrushTracker1D.tsx
- src/component/EventsTrackers/BrushTracker.tsx
the bug was introduced in the commit #2ce8ef9
close #3378
> fix: convert range from Pixel to PPM

- package-lock.json
- package.json
- src/component/1d/ApodizationLine.tsx
- src/component/1d/ranges/Range.tsx
- src/component/1d/tool/BaseLine.tsx
- src/component/1d/tool/PivotIndicator1D.tsx
- src/component/2d/tools/PivotIndicator.tsx
- src/component/hooks/useIndicatorLineColor.ts
- src/component/modal/setting/GeneralSettings.tsx
- src/component/modal/setting/settings-tabs/DisplayTabContent.tsx
- src/component/modal/setting/settings-tabs/GeneralTabContent.tsx
- src/component/modal/setting/settings-tabs/InfoBlockTabContent.tsx
- src/component/modal/setting/settings-tabs/OnLoadProcessingTabContent.tsx
- src/component/modal/setting/settings-tabs/SpectraColorsTabContent.tsx
- src/component/reducer/actions/LoadActions.ts
- src/component/workspaces/workspaceDefaultProperties.ts
- src/demo/views/BenchtopNMRWorkspace.tsx
> feat: customize tools indicator line color

- package-lock.json
- package.json
- src/component/hooks/useToolsFunctions.ts
- src/component/panels/Panels.tsx
- src/component/panels/accordionItems.tsx
- src/component/panels/databasePanel/DatabasePanel.tsx
- src/component/panels/predictionPanel/PredictionPanel.tsx
> refactor: improve tools panels mapping

- package-lock.json
- package.json
- src/component/panels/PanelsBar.tsx
- test-e2e/panels/integral.test.ts
Fixes bugs related to embedding NMRium in a project using tailwindcss
> fix: update react-science

- package-lock.json
- package.json
- src/component/panels/databasePanel/DatabasePanel.tsx
- src/component/panels/databasePanel/DatabasePreferences.tsx
- src/component/panels/databasePanel/DatabaseSearchOptions.tsx
- src/component/panels/databasePanel/DatabaseTable.tsx
- src/component/reducer/actions/DatabaseActions.ts
- src/component/reducer/actions/MoleculeActions.ts
- src/component/reducer/preferences/panelsPreferencesDefaultValues.ts
- src/data/molecules/MoleculeManager.ts
* refactor: database counter
feat: add/remove a molecule from the database
* feat: switch to 'stack' mode when adding a spectrum from the database
* chore: update nmr-load-save to version 3.4.0
feat: control structure size (default minHeight: 100px)
> feat: improve database (#3455)

- package-lock.json
- package.json
- src/component/panels/databasePanel/DatabasePanel.tsx
- src/component/panels/databasePanel/DatabasePreferences.tsx
- src/component/panels/databasePanel/DatabaseSearchOptions.tsx
- src/component/panels/databasePanel/DatabaseTable.tsx
- src/component/reducer/actions/DatabaseActions.ts
- src/component/reducer/actions/MoleculeActions.ts
- src/component/reducer/preferences/panelsPreferencesDefaultValues.ts
- src/data/molecules/MoleculeManager.ts
* refactor: database counter
feat: add/remove a molecule from the database
* feat: switch to 'stack' mode when adding a spectrum from the database
* chore: update nmr-load-save to version 3.4.0
feat: control structure size (default minHeight: 100px)
> feat: improve database panel (#3455)

- src/component/1d/FloatPublicationString.tsx
- src/component/1d/ranges/AssignmentLabel.tsx
- src/component/1d/ranges/Range.tsx
- src/component/1d/ranges/Ranges.tsx
- src/component/2d/SVGContent2D.tsx
- src/component/2d/utilities/extractSpectrumSignals.ts
- src/component/2d/zones/SignalsGuideLines.tsx
- src/component/2d/zones/Zone.tsx
- src/component/hooks/useCanvasContext.ts
- src/component/panels/RangesPanel/TableColumns/RangeAssignmentColumn.tsx
- src/component/reducer/actions/RangesActions.ts
https://assign-2d-1d.nmrium.pages.dev/
> feat: assign 1D labels from 2D spectra

- src/component/reducer/helper/removeSpectrumRelatedObjectsById.ts
> feat: remove related insets when a spectrum is deleted

- src/component/reducer/actions/DomainActions.ts
- src/component/reducer/helper/Zoom1DManager.ts
refactor: remove rescaling using d3
refactor: rescale spectra to same top
refactor: reset spectra scale
> refactor: simplify rescaling

- package-lock.json
- package.json
- vite.config.ts
The latest version causes a bug in some components and we don't use it in other projects
> chore: remove vite plugin-react-swc

- src/component/1d-2d/components/FloatMoleculeStructures/DraggableStructure.tsx
- src/component/1d/FloatPublicationString.tsx
- src/component/1d/FloatingRanges.tsx
- src/component/1d/inset/DraggableInset.tsx
> fix: use selector for ReactRnd bounds

- src/component/1d/XAxis1D.tsx
> refactor: hide inset scale grid

- src/component/1d-2d/components/SpectrumInfoBlock.tsx
> refactor: hide title block on insets

- src/component/2d/utilities/extractSpectrumSignals.ts
- src/component/2d/zones/SignalsGuideLines.tsx
- src/data/data1d/Spectrum1D/isRangeAssigned.ts
> feat: add yellow highlight to assigned 2D signals
