src/component/panels/IntegralTablePanel.jsx, src/component/panels/PeaksTablePanel.jsx, src/component/panels/RangesTablePanel.jsx
usage of "basic" sorting of numeric values in React Tables (for numbers between 0 and 1) + showing of symbols and units in header of couplings (J) and delta (greek uppercase delta) of signals
=> Changes in React table sorting and addition of symbols in sub-table headers 

src/component/panels/MoleculePanel.jsx, src/data/Analysis.js
1) sets now the correct reference value if the activeTab is switched and another molecule than the first one is in current view
2) when editing a molecule: if we save a fully connected molecule then it keeps its key and position in the molecules list, instead of deleting it and push a new molecule object at the list end (incl. new key)
=> Two fixes in context of molecules and setting reference values (sums) 

src/component/1d/IntegralResizable.jsx, src/component/modal/NumberInputModal.jsx, src/component/panels/IntegralTablePanel.jsx, src/component/panels/RangesTablePanel.jsx, src/component/panels/preferences-panels/IntegralsPreferences.jsx, src/component/panels/preferences-panels/defaultValues.js, src/component/reducer/actions/RangesActions.js, src/data/Analysis.js, src/data/data1d/Datum1D.js, src/data/data1d/detectSignal.js
- when editing a molecule: if we save a fully connected molecule then it keeps its key and position in the molecules list, instead of deleting it and push a new molecule object at the list end (incl. new keys)
- changed name fields in Integral to "absolute" and "integral"; 
- integrals and ranges with kind different than "signal" are not considered for relative number of element (e.g. total number of H's) anymore
- modifications towards a more general method for updating relative values (updateRelatives() )
- fix: Analysis.js -> add missing ranges to returned object
- sets the options.sum for ranges and integrals in Datum1D constructor to default of 100
- a new separate detectSignal() method and class
- from/to values for signals are stored now, for each signal within ranges
- hovering …
=> reimplementing previous commits

src/component/1d/IntegralResizable.jsx, src/component/1d/Range.jsx, src/component/panels/IntegralTablePanel.jsx, src/component/panels/PeaksTablePanel.jsx, src/component/panels/RangesTablePanel.jsx, src/data/data1d/Datum1D.js
- bugfix: #454 
- peak value (Hz) in table is shown in Hz now: #428 
- replaced absolute by relative value at the bottom of Integrals, the other part (coloring) was already done by @hamed-musallam if I saw it correctly: #433 
- excluded relative integral values in tables are now displayed in brackets -> [0.00]
- non-signal ranges in spectrum appear semi transparent (green rectangle and label)
=> Bugfix, issue closes and non-signal ranges appear semi transparent

src/component/1d/Range.jsx, src/component/header/RangesPickingOptionPanel.jsx, src/component/panels/RangesPanel/RangesTableRow.jsx, src/data/data1d/Datum1D.js
The error comes from highlight functionality when diaID does not exist, we should not assign an empty array to diaID because we could include ranges assigned in the future.
=> fix(autoRanges): avoid throw error when diaID does not exist

src/component/panels/MoleculesPanel/MoleculePanel.tsx
Closes: https://github.com/cheminfo/nmrium/issues/1341
@lpatiny Actually i have that (with this fix)
Do this works with your example ?
=> Change the dom to not allow the "Structures" panel to expand

src/component/NMRium.tsx, src/component/utility/Export.ts
@targos 
we use useImperativeHandle to customize the instance value that is exposed to parent components when using ref so it is possible to call the generate a Blob function, and then they can do whatever they need with this blob, to store it in the database or save as png or svg  ... etc in an external file server.
https://github.com/cheminfo/nmrium/issues/1569
=> feat: generate blob for the spectra from an outside component

package-lock.json, package.json, src/component/NMRium.tsx, src/component/hooks/useExport.tsx, src/component/modal/ExportAsMatrixModal.tsx, src/component/panels/MoleculesPanel/MoleculePanelHeader.tsx, src/component/panels/MultipleSpectraAnalysisPanel/MultipleSpectraAnalysisPanel.tsx, src/component/panels/RangesPanel/RangesHeader.tsx, src/component/panels/RangesPanel/RangesPanel.tsx, src/component/panels/SpectrumsPanel/SpectrumsTabs.tsx, src/component/utility/export.ts, src/demo/views/Exam.tsx
- use a new package "clipboard-polyfill" as a temporary solution until the Firefox team implement ClipboardItem. 
- remove the hack way we use to copy HTML to the clipboard for Firefox. 
- rename the file from "Export" to "export"
=> refactor: export utility

src/component/reducer/preferences/actions/initPreferences.ts
set default workspace if the specified workspace does not exists in the workspaces object
close #1979
=> fix: set `default` workspace if the specified workspace does not exists

src/component/elements/ReactTable/ReactTable.tsx
wait for the container height value before calculating the virtual scroll boundary
=> chore: fix react table virtual scroll

src/component/modal/SaveAsModal.tsx
=> refactor: disable 'export as data source' if the 'baseURL' is not exists

package-lock.json, package.json, public/data/aspirin/aspirin_bruker_files.json, public/data/aspirin/bruker_aspirin_zip.json, public/data/brukerFolders/brukerFolderWithoutExpno.json, public/data/cytisine/1H_Cytisin_linkJcamp.json, public/data/cytisine/2d/jresolv.json, public/data/nmriumFromSource.json, src/component/loader/DropZone.tsx, src/component/panels/databasePanel/DatabaseStructureSearchModal.tsx
the idea is to filter jcamp data without parse completely the jcamp file. The filtering will works by the LDR `DATA_TYPE` and `DATA_CLASS`
fid data will expect:
DATA_TYPE  includes `FID`
ft data will expect
DATA_TYPE  includes `SPECTRUM`
DATA_CLASS  not includes `PEAK `
it should close too;
- #2130
=> fix: extend preference dataSelection to jcamp format

src/component/1d/Line.tsx, src/component/utility/parseColor.ts
We parse the color to extract the color in hex and the alpha and convert the alpha hex value to a decimal value between 0 and  1.
https://github.com/cheminfo/nmrium/blob/2cdf4dd99c16f44f1434a495d8941ef1619a6be0/src/component/utility/parseHexaColor.ts#L1-L20
This should solve the problem of why the spectra are not visible when the import the exported SVG  to MS World
=> fix: parse hex color and extract opacity

src/component/1d/multiplicityTree/MultiplicityTree.tsx, src/component/1d/ranges/LinkButton.tsx, src/component/1d/ranges/Range.tsx, src/component/1d/ranges/Ranges.tsx, src/component/elements/Button.tsx, src/component/highlight/index.tsx
To make it easy to assign range or signal directly from the multiplicity tree or from the range, right now we have little green buttons at the level of range on the top right corner of the range and at each signal multiplicity tree on the left side of the tree.
you can simply click on the button (its color will change from green to red to indicate you are in the middle of the assignment process for range or signal ) and then select the atom that you want to assign to.
=> feat: improve assignments

src/component/modal/MultipletAnalysisModal.tsx, src/data/data1d/Spectrum1D/ranges/__tests__/detectSignal.test.ts, src/data/data1d/Spectrum1D/ranges/detectSignal.ts
the symmetry check will be manage by multiplet-analysis package and we will use signalJoinCouplings to merge couplings, e.g. the pattern `dd` with closer coupling values into `t` based in a `tolerance` option.
=> check symmetry first for manual range picking

package-lock.json, package.json
correct mapping of the nucleus name by jeol to nmr-processing constants
=> manage correctly 19F n 31P jeol data

src/component/loader/NoData.tsx
The children are not necessarily a simple string and it's not allowed
to have for example div as the child of p.
=> fix: do not use p element in NoData component

package-lock.json, package.json
somes logs are not useful e.g when any spectra is loaded, it is related with: 
- https://github.com/cheminfo/nmr-load-save/issues/225
=> chore: move some logs to debug level

src/data/PredictionManager.ts
- calculate the spectralWidth for 2D predicted spectra
=> fix: manual zones detection for predicted 2D spectra

src/component/NMRium.tsx
This way we can wrap it with a different error boundary.
=> feat: allow to render NMRium without error boundary

src/component/header/ZeroFillingOptionsPanel.tsx, src/component/modal/PredictSpectraModal.tsx, src/component/panels/filtersPanel/FiltersTable.tsx
Refs: https://github.com/cheminfo/nmrium/issues/2406
=> 2406 replace with checkbox component from react science

src/component/1d/tool/BaseLineZones.tsx
They should only appear and be removable when the baseline correction tool is selected.
close #2348
=> fix: baseline correction zones visibility

.eslintrc.yml, src/component/1d/ApodizationLine.tsx, src/component/1d/Line.tsx, src/component/1d/ranges/Range.tsx, src/component/2d/ft/Contours.tsx, src/component/elements/popup/Modal/ConfirmDialog.tsx, src/component/main/InnerNMRiumContents.tsx, src/component/panels/SpectrumsPanel/base/ShowHideSpectrumButton.tsx, src/demo/views/Test.tsx, test-e2e/NmriumPage.ts, test-e2e/core/basic.test.ts, test-e2e/panels/filters.test.ts, test-e2e/panels/ranges.test.ts, test-e2e/panels/spectra.test.ts, test-e2e/panels/structures.test.ts
this is the standard for testing with playwright.
use getByTestId("name") instead locator('[data-test-id="name"]')
Closes: https://github.com/cheminfo/nmrium/issues/2584
=> refactor: data-test-id to data-testid

package-lock.json, package.json
chore: update nmr-load-save to version 0.23.4
=> fix: read gyromagnetic ratio correctly

package-lock.json, package.json, test-e2e/panels/ranges.test.ts
Also with version 0.23.6 of nmr-load-save, the molfile could be generated from `jcamp-cs` data, thanks to using the new feature `parseJcampCS`in jcampconverter
=> fix: jcamp tree filtering n wrong scale on F1

package-lock.json, src/component/1d/Viewer1D.tsx, src/component/2d/zones/Signal.tsx, src/component/assignment/AssignmentsContext.ts, src/component/panels/RangesPanel/RangesTableRow.tsx, src/component/panels/RangesPanel/TableColumns/ActionsColumn.tsx, src/component/panels/RangesPanel/TableColumns/SignalDeltaColumn.tsx, src/component/panels/RangesPanel/hooks/useMapRanges.ts, src/data/data1d/Spectrum1D/ranges/__tests__/detectSignal.test.ts, src/data/data1d/Spectrum1D/ranges/addRange.ts, src/data/data1d/Spectrum1D/ranges/changeRange.ts, src/data/data1d/Spectrum1D/ranges/detectSignal.ts, src/data/data1d/Spectrum1D/ranges/detectSignals.ts, test-e2e/panels/ranges.test.ts
do not use multilplet-analysis in
=> fix: add peaks in manual range picking

src/component/panels/SpectrumsPanel/SpectraPanelHeader.tsx
=> refactor: display the number of spectra in the corresponding panel

package-lock.json, package.json
fix: check spectrum has imaginary part before calling xMultiply
=> chore: update nmr-load-save to version 0.23.10

src/data/data1d/Spectrum1D/ranges/detectSignals.ts, src/data/data1d/Spectrum1D/ranges/detectSignalsByMultipletAnalysis.ts
when data length is less than 4092 multiplet-analysis package is used
multiplet-analysis does not returns peaks, so an automatic peak picking is done on the ROI
=> fix: add missing peaks when use multiplet-analysis

src/component/main/InnerNMRium.tsx
This leads to random crashes because browser translation manipulates the
DOM in a way that React can be confused.
=> fix: disable auto-translate of the NMRium component

.github/workflows/nodejs.yml
The codecov comments are not very relevant in this project as most files are tested through Playwright instead of unit tests.
=> chore: disable coverage reports for tests

src/component/1d/Viewer1D.tsx, src/component/2d/Viewer2D.tsx, src/component/EventsTrackers/BrushTracker.tsx, src/component/reducer/actions/ToolsActions.ts, src/component/reducer/helper/Zoom1DManager.ts, src/data/data2d/Spectrum2D/contours.ts
=> feat: zoom in/out with the mouse wheel

src/data/data2d/Spectrum2D/getSlice.ts, test-e2e/tools/slicing.test.ts
We have encountered a major bug that causes failures in the slicing tool and 2D phase correction tool. This issue was introduced by the PR 
- https://github.com/cheminfo/nmrium/pull/2949
=> fix: set the size correctly for real part in slicing function

src/component/modal/setting/GeneralSettings.tsx
In Blueprint.js version 5.10.4, the tab component has a fixed 20px gap between the tab list items
=> style: set tab list item gap to 0

src/component/panels/Panels.tsx
- Simplify the toolbar specifically for the information panel as a temporary solution until we enhance the information table to include editing capabilities within it.
- Disable the edit button when no spectrum is selected, and display a tooltip when hovering over it "Select a spectrum to edit its meta information".
=> refactor: improve information panel toolbar

package-lock.json, package.json, src/component/2d/Viewer2D.tsx, src/component/context/ChartContext.tsx, src/component/elements/PrintContent.tsx, src/component/elements/print/PrintContent.tsx, src/component/elements/print/PrintProvider.tsx, src/component/elements/print/index.ts, src/component/main/InnerNMRiumContents.tsx, src/component/main/NMRiumViewer.tsx, src/component/reducer/preferences/actions/changePrintPageSettings.ts, src/component/reducer/preferences/preferencesReducer.ts, src/component/workspaces/workspaceDefaultProperties.ts, src/demo/Sidebar.tsx, src/demo/index.css, src/demo/layouts/Admin.tsx
=> feat: print spectra

src/data/data1d/Spectrum1D/ranges/detectSignals.ts
the coupling can be as big as the size of the range in Hz.
=> fix: allow big couplings when a range is added manually

src/component/elements/CheckController.tsx, src/component/elements/FormatField.tsx, src/component/elements/NumberInput2Controller.tsx, src/component/panels/IntegralsPanel/IntegralPanel.tsx, src/component/panels/IntegralsPanel/IntegralsPreferences.tsx, src/component/panels/PeaksPanel/PeaksPanel.tsx, src/component/panels/PeaksPanel/PeaksPreferences.tsx, src/component/panels/RangesPanel/RangesPreferences.tsx, src/component/panels/ZonesPanel/ZonesPanel.tsx, src/component/panels/ZonesPanel/ZonesPreferences.tsx, src/component/panels/extra/preferences/NucleusPreferences.tsx, src/component/panels/extra/utilities/settingImperativeHandle.ts
Use React Hook Form instead of Formik in panels preferences
=> refactor: panels preferences

src/component/1d/SpectraLegends.tsx
When one or more spectra are selected, display tracking for those specific spectra. If no spectra are selected, display tracking for all available spectra
close #3231
=> feat: display tracking for selected spectra

src/component/1d/FloatingRanges.tsx, src/component/panels/RangesPanel/RangesTable.tsx, src/component/utility/extractChemicalElement.ts
- rename the relative column header in 'floating ranges' to be based on the corresponding chemical element
=> refactor: rename relative column header in ranges

src/component/EventsTrackers/BrushTracker.tsx, test-e2e/panels/integral.test.ts
Playwright's mousedown, move, and mouseup events do not trigger a click event, preventing me from reproducing the issue in Playwright to write a test case.
=> fix: prevent click event if the user dragged the mouse

src/component/1d/BrushTracker1D.tsx, src/component/panels/multipleAnalysisPanel/base/AnalysisColumnHeader.tsx
Resolve a bug introduced by commit #b164290
=> fix: pass start and end in PPM for 'ANALYZE_SPECTRA' action

src/component/elements/export/ExportManager.tsx, src/component/hooks/useExport.tsx, src/component/panels/MoleculesPanel/MoleculePanelHeader.tsx, src/component/panels/multipleAnalysisPanel/AnalysisChart.tsx, src/component/utility/export.ts
=> refactor: catch and display export error correctly

package-lock.json, package.json
Greatly improves rendering of the molecule editor on hidpi screens.
Release-as: v0.63.0
=> fix: update OpenChemLib to v9.1.1

src/component/panels/predictionPanel/PredictionPanel.tsx
- Better sizing on small screen
- Remove unneeded scrollbar
- Avoid molecule recentering while it's edited
=> fix: prediction panel usability

src/component/panels/MatrixGenerationPanel/MatrixGenerationPanel.tsx
Memoized the initialValues passed to useWatchForm im matrix generation panel to avoid triggering reset on every render due to a new object reference.
=> fix: prevent unnecessary re-renders

package-lock.json, package.json
- move @blueprintjs/core,  @blueprintjs/icons and @blueprintjs/select to peerDependencies and devDependencies
=> chore: move blueprintjs to peerDependencies

src/component/1d/inset/DraggableInset.tsx
hide ranges actions if no ranges, peaks actions if no peaks, and integrals actions if no integrals
=> refactor: inset action buttons
